# frozen_string_literal: true
source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "pg", ">= 0.18"
gem "puma", "~> 5.0"
gem "redis", "~> 4.0"
gem "sidekiq"

group :development, :test do
  gem "rspec-rails"
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "rubocop"
end
